name: lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  Lint:
    name: Lint
    env:
      GO_VERSION: '1.21'
      GOPRIVATE: 'github.com/Layr-Labs/cerberus-api'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Configure Git for private modules
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global url."https://${{ github.token }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60